# spring:
#   cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
#           lower-case-service-id: true  #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
#       routes:
#         #- id: host_route
#         - id: liuwenjie_route
#           uri: lb://server
#           predicates:
#             - Path=/status
#         - id: path_route
#           uri: lb://server  # 或 http://127.0.0.1:8081
#           predicates:
#             - Path=/getName
#             - Query=smile    # 请求中必须包含这个参数名
#         - id: order_route
#           uri: lb://server
#           predicates:
#             - Path=/**        # 其余的请求直接转发
        #- id: path_route
        #  uri: lb://server   # 使用nacos 服务注册中的服务名
        #  predicates:
        #    - Path=/index
        #    - Query=smile,pu..  # 请求中包含 keep 属性并且参数值是以 pu 开头的长度为四位的字符串才会进行匹配和路由, http://127.0.0.1:8888/?smile=pubb
