spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: host_route
          uri: lb://server
          predicates:
            - Path=/status
        - id: name_route
          uri: lb://server
          predicates:
            - Path=/getName
        - id: config_route
          uri: lb://server
          predicates:
            - Path=/config/get
        - id: mysql_route
          uri: lb://server
          predicates:
            - Path=/selectFromMysql
            - Path=/insertToMysql
        - id: redis_route
          uri: lb://server
          predicates:
            - Path=/selectFromRedis
        - id: rocket_route
          uri: lb://server
          predicates:
            - Path=/syncMessage
            - Path=/sendMessage
