spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: host_route
          uri: lb://server
          predicates:
            - Path=/status
        - id: name_route
          uri: lb://server
          predicates:
            - Path=/getName
        - id: config_route
          uri: lb://server
          predicates:
            - Path=/config/get
        - id: mysql_select_route
          uri: lb://server
          predicates:
            - Path=/selectFromMysql
        - id: mysql_insert_route
          uri: lb://server
          predicates:
            - Path=/insertToMysql
        - id: redis_route
          uri: lb://server
          predicates:
            - Path=/selectFromRedis
        - id: rocket_send_route
          uri: lb://server
          predicates:
            - Path=/sendMessage
        - id: rocket_sync_route
          uri: lb://server
          predicates:
            - Path=/syncMessage      
        
        
        #- id: order_route
        #  uri: lb://server
        #  predicates:
        #    - Path=/**

 
