version: '3.5'

services:
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos_svc
    ports: 
      - 8079:8848
    environment:
      MODE: standalone
    networks:
      rmq:
        aliases:
          - nacos

  sentinel:
    image: lwx372123/sentinel:v1
    container_name: sentinel_svc
    ports:
      - 8080:8080
    networks:
      rmq:
        aliases:
          - sentinel
  
  redis:
    image: lwx372123/redis:v1
    container_name: redis_svc
    ports:
      - 8082:6379
    volumes:
      - /root/persistence/redis:/data
    networks:
      rmq:
        aliases:
          - redis

  mysql:
    image: mysql:5.7
    container_name: mysql_svc
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: Aliyun-test
    volumes:
      - /root/persistence/mysql:/var/lib/mysql
    networks:
      rmq:
        aliases:
          - mysql




  rmqnamesrv:
    image: foxiswho/rocketmq:4.8.0
#    image: registry.cn-hangzhou.aliyuncs.com/foxiswho/rocketmq:4.7.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./rmqs/logs:/home/rocketmq/logs
      - ./rmqs/store:/home/rocketmq/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: ["sh","mqnamesrv"]
    networks:
        rmq:
          aliases:
            - rmqnamesrv

  rmqbroker:
    image: foxiswho/rocketmq:4.8.0
#    image: registry.cn-hangzhou.aliyuncs.com/foxiswho/rocketmq:4.7.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - /root/persistence/rocketmq/rmq/logs:/home/rocketmq/logs
      - /root/persistence/rocketmq/rmq/store:/home/rocketmq/store
      - ./brokerconf/broker.conf:/etc/rocketmq/broker.conf
    environment:
        JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","rmqnamesrv:9876","autoCreateTopicEnable=true"]
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqbroker

  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8180:8080
    environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqconsole

networks:
  rmq:
    name: rmq
    driver: bridge

